- hosts: localhost
  become: true
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
  roles:
    - role: deploy-git
    - role: deploy-docker
    - role: deploy-frontend
    - role: deploy-backend

- hosts: harvester_instance
  become: true
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
  tasks:
    - name: Clone harvest repository
      git:
        repo: "{{my_harvest_repo}}"
        dest: "{{root_path}}{{harvest_path}}"
        version: main
        force: yes #rewrite

    - name: change file permissions for harvest
      file:
          path: "{{root_path}}{{harvest_path}}"
          mode: '0777'
          recurse: yes

- hosts: harvester_instance
  become: true
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
  roles:
    - role: deploy-docker
    - role: deploy-harvester




